import {
  LayoutDashboard,
  Clock,
  BookOpenCheck,
  ClipboardCheck,
  GraduationCap,
  FileSpreadsheet,
  CalendarDays,
  CalendarRange,
  FileText,
  UserSquare2,
  Users,
  BookOpen,
  UserCog,
  Sliders,
  Image as ImageIcon,
  type LucideIcon
} from 'lucide-react';

export interface MenuTheme {
  id: string;
  label: string;
  shortLabel: string;
  category: string;
  desc: string;
  icon: LucideIcon;
  colorName: string;
  // Colors
  primaryHex: string;
  gradient: string;
  softBg: string;
  borderColor: string;
  badgeBg: string;
  badgeText: string;
  badgeBorder: string;
  textColor: string;
  // Sidebar active style
  sidebarActiveBg: string;
  sidebarActiveText: string;
  sidebarActiveShadow: string;
  // Inactive icon container
  iconContainerBg: string;
  iconContainerText: string;
}

export const MENU_THEMES: Record<string, MenuTheme> = {
  // -------------------------------------------------------------
  // GURU MENUS
  // -------------------------------------------------------------
  'guru-dashboard': {
    id: 'guru-dashboard',
    label: 'Dashboard Guru',
    shortLabel: 'Dashboard',
    category: 'Pusat Kerja',
    desc: 'Jadwal Hari Ini, Agenda Mendesak & Ringkasan Kelas',
    icon: LayoutDashboard,
    colorName: 'indigo',
    primaryHex: '#4F46E5',
    gradient: 'from-indigo-600 via-indigo-700 to-indigo-800',
    softBg: 'bg-indigo-50/70',
    borderColor: 'border-indigo-200',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-800',
    badgeBorder: 'border-indigo-200',
    textColor: 'text-indigo-700',
    sidebarActiveBg: 'bg-gradient-to-r from-indigo-600 to-indigo-700',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-indigo-500/25',
    iconContainerBg: 'bg-indigo-100/70',
    iconContainerText: 'text-indigo-600'
  },
  'guru-jadwal': {
    id: 'guru-jadwal',
    label: 'Jadwal Mengajar',
    shortLabel: 'Jadwal',
    category: 'Agenda Harian',
    desc: 'Jadwal Tatap Muka, Jam Pembelajaran & Ruang Kelas',
    icon: Clock,
    colorName: 'amber',
    primaryHex: '#D97706',
    gradient: 'from-amber-500 via-amber-600 to-orange-600',
    softBg: 'bg-amber-50/70',
    borderColor: 'border-amber-200',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-800',
    badgeBorder: 'border-amber-200',
    textColor: 'text-amber-700',
    sidebarActiveBg: 'bg-gradient-to-r from-amber-500 to-orange-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-amber-500/25',
    iconContainerBg: 'bg-amber-100/70',
    iconContainerText: 'text-amber-600'
  },
  'guru-jurnal': {
    id: 'guru-jurnal',
    label: 'Jurnal Mengajar',
    shortLabel: 'Jurnal',
    category: 'Agenda Harian',
    desc: 'Catatan Harian Kelas, Materi, Capaian & Hambatan',
    icon: BookOpenCheck,
    colorName: 'sky',
    primaryHex: '#0284C7',
    gradient: 'from-sky-500 via-sky-600 to-blue-600',
    softBg: 'bg-sky-50/70',
    borderColor: 'border-sky-200',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-800',
    badgeBorder: 'border-sky-200',
    textColor: 'text-sky-700',
    sidebarActiveBg: 'bg-gradient-to-r from-sky-500 to-blue-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-sky-500/25',
    iconContainerBg: 'bg-sky-100/70',
    iconContainerText: 'text-sky-600'
  },
  'guru-absensi': {
    id: 'guru-absensi',
    label: 'Absensi Siswa',
    shortLabel: 'Absensi',
    category: 'Kegiatan Kelas',
    desc: 'Presensi Harian Siswa, Rekap Hadir, Sakit, Izin & Alpha',
    icon: ClipboardCheck,
    colorName: 'teal',
    primaryHex: '#0D9488',
    gradient: 'from-teal-500 via-teal-600 to-emerald-600',
    softBg: 'bg-teal-50/70',
    borderColor: 'border-teal-200',
    badgeBg: 'bg-teal-100',
    badgeText: 'text-teal-800',
    badgeBorder: 'border-teal-200',
    textColor: 'text-teal-700',
    sidebarActiveBg: 'bg-gradient-to-r from-teal-500 to-emerald-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-teal-500/25',
    iconContainerBg: 'bg-teal-100/70',
    iconContainerText: 'text-teal-600'
  },
  'guru-nilai': {
    id: 'guru-nilai',
    label: 'Nilai Siswa (Asesmen)',
    shortLabel: 'Nilai Siswa',
    category: 'Evaluasi & Asesmen',
    desc: 'Pengelolaan Nilai Formatif, Sumatif, STS, SAS & Predikat KKTP',
    icon: GraduationCap,
    colorName: 'purple',
    primaryHex: '#9333EA',
    gradient: 'from-purple-600 via-purple-700 to-fuchsia-600',
    softBg: 'bg-purple-50/70',
    borderColor: 'border-purple-200',
    badgeBg: 'bg-purple-100',
    badgeText: 'text-purple-800',
    badgeBorder: 'border-purple-200',
    textColor: 'text-purple-700',
    sidebarActiveBg: 'bg-gradient-to-r from-purple-600 to-fuchsia-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-purple-500/25',
    iconContainerBg: 'bg-purple-100/70',
    iconContainerText: 'text-purple-600'
  },
  'guru-rekap': {
    id: 'guru-rekap',
    label: 'Rekap dan Laporan',
    shortLabel: 'Rekap & Leger',
    category: 'Evaluasi & Asesmen',
    desc: 'Leger Nilai Akhir Raport, Rekap Absensi & Cetak Dokumen Resmi',
    icon: FileSpreadsheet,
    colorName: 'rose',
    primaryHex: '#E11D48',
    gradient: 'from-rose-500 via-rose-600 to-pink-600',
    softBg: 'bg-rose-50/70',
    borderColor: 'border-rose-200',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-800',
    badgeBorder: 'border-rose-200',
    textColor: 'text-rose-700',
    sidebarActiveBg: 'bg-gradient-to-r from-rose-500 to-pink-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-rose-500/25',
    iconContainerBg: 'bg-rose-100/70',
    iconContainerText: 'text-rose-600'
  },
  'guru-promes': {
    id: 'guru-promes',
    label: 'Program Semester',
    shortLabel: 'Promes',
    category: 'Perangkat Kurikulum',
    desc: 'Distribusi Jam Pembelajaran & Pekan Efektif Semester',
    icon: CalendarDays,
    colorName: 'cyan',
    primaryHex: '#0891B2',
    gradient: 'from-cyan-600 via-teal-600 to-blue-600',
    softBg: 'bg-cyan-50/70',
    borderColor: 'border-cyan-200',
    badgeBg: 'bg-cyan-100',
    badgeText: 'text-cyan-800',
    badgeBorder: 'border-cyan-200',
    textColor: 'text-cyan-700',
    sidebarActiveBg: 'bg-gradient-to-r from-cyan-600 to-teal-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-cyan-500/25',
    iconContainerBg: 'bg-cyan-100/70',
    iconContainerText: 'text-cyan-600'
  },
  'guru-prota': {
    id: 'guru-prota',
    label: 'Program Tahunan',
    shortLabel: 'Prota',
    category: 'Perangkat Kurikulum',
    desc: 'Pemetaan Capaian Pembelajaran (CP) & Alokasi JP Tahunan',
    icon: CalendarRange,
    colorName: 'blue',
    primaryHex: '#2563EB',
    gradient: 'from-blue-600 via-indigo-600 to-sky-600',
    softBg: 'bg-blue-50/70',
    borderColor: 'border-blue-200',
    badgeBg: 'bg-blue-100',
    badgeText: 'text-blue-800',
    badgeBorder: 'border-blue-200',
    textColor: 'text-blue-700',
    sidebarActiveBg: 'bg-gradient-to-r from-blue-600 to-indigo-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-blue-500/25',
    iconContainerBg: 'bg-blue-100/70',
    iconContainerText: 'text-blue-600'
  },
  'guru-modul': {
    id: 'guru-modul',
    label: 'Modul Ajar & LKPD',
    shortLabel: 'Modul & LKPD',
    category: 'Perangkat Kurikulum',
    desc: 'RPP Merdeka, Modul Ajar Tematik & Lembar Kerja Peserta Didik',
    icon: FileText,
    colorName: 'violet',
    primaryHex: '#7C3AED',
    gradient: 'from-violet-600 via-purple-600 to-indigo-600',
    softBg: 'bg-violet-50/70',
    borderColor: 'border-violet-200',
    badgeBg: 'bg-violet-100',
    badgeText: 'text-violet-800',
    badgeBorder: 'border-violet-200',
    textColor: 'text-violet-700',
    sidebarActiveBg: 'bg-gradient-to-r from-violet-600 to-purple-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-violet-500/25',
    iconContainerBg: 'bg-violet-100/70',
    iconContainerText: 'text-violet-600'
  },
  'guru-siswa': {
    id: 'guru-siswa',
    label: 'Master Data Siswa',
    shortLabel: 'Data Siswa',
    category: 'Data Pokok',
    desc: 'Buku Induk Peserta Didik, NISN, Kelas & Kontak Orang Tua',
    icon: UserSquare2,
    colorName: 'emerald',
    primaryHex: '#059669',
    gradient: 'from-emerald-600 via-teal-600 to-green-600',
    softBg: 'bg-emerald-50/70',
    borderColor: 'border-emerald-200',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
    badgeBorder: 'border-emerald-200',
    textColor: 'text-emerald-700',
    sidebarActiveBg: 'bg-gradient-to-r from-emerald-600 to-teal-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-emerald-500/25',
    iconContainerBg: 'bg-emerald-100/70',
    iconContainerText: 'text-emerald-600'
  },

  // -------------------------------------------------------------
  // ADMIN MENUS
  // -------------------------------------------------------------
  'admin-dashboard': {
    id: 'admin-dashboard',
    label: 'Dashboard Administrator',
    shortLabel: 'Dashboard Admin',
    category: 'Pusat Kendali',
    desc: 'Statistik Sekolah, Monitoring Beban Mengajar & Kelengkapan Berkas',
    icon: LayoutDashboard,
    colorName: 'indigo',
    primaryHex: '#4338CA',
    gradient: 'from-indigo-700 via-indigo-800 to-slate-900',
    softBg: 'bg-indigo-50/70',
    borderColor: 'border-indigo-200',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-900',
    badgeBorder: 'border-indigo-300',
    textColor: 'text-indigo-800',
    sidebarActiveBg: 'bg-gradient-to-r from-indigo-700 to-indigo-900',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-indigo-600/30',
    iconContainerBg: 'bg-indigo-100',
    iconContainerText: 'text-indigo-700'
  },
  'admin-jadwal': {
    id: 'admin-jadwal',
    label: 'Jadwal Pelajaran Sekolah',
    shortLabel: 'Master Jadwal',
    category: 'Manajemen Akademik',
    desc: 'Master Jadwal Pelajaran Sekolah & Distribusi Jam Tatap Muka Guru',
    icon: Clock,
    colorName: 'amber',
    primaryHex: '#B45309',
    gradient: 'from-amber-600 via-amber-700 to-orange-700',
    softBg: 'bg-amber-50/70',
    borderColor: 'border-amber-200',
    badgeBg: 'bg-amber-100',
    badgeText: 'text-amber-900',
    badgeBorder: 'border-amber-300',
    textColor: 'text-amber-800',
    sidebarActiveBg: 'bg-gradient-to-r from-amber-600 to-orange-700',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-amber-600/30',
    iconContainerBg: 'bg-amber-100',
    iconContainerText: 'text-amber-700'
  },
  'admin-users': {
    id: 'admin-users',
    label: 'Kelola Akun Pengguna',
    shortLabel: 'Akun Pengguna',
    category: 'Keamanan & Akses',
    desc: 'Manajemen Hak Akses, Akun Administrator & Kredensial Guru',
    icon: UserCog,
    colorName: 'slate',
    primaryHex: '#334155',
    gradient: 'from-slate-700 via-slate-800 to-zinc-900',
    softBg: 'bg-slate-100/70',
    borderColor: 'border-slate-300',
    badgeBg: 'bg-slate-200',
    badgeText: 'text-slate-800',
    badgeBorder: 'border-slate-300',
    textColor: 'text-slate-800',
    sidebarActiveBg: 'bg-gradient-to-r from-slate-700 to-slate-900',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-slate-700/30',
    iconContainerBg: 'bg-slate-200',
    iconContainerText: 'text-slate-700'
  },
  'admin-guru': {
    id: 'admin-guru',
    label: 'Master Data Tenaga Pendidik',
    shortLabel: 'Data Guru',
    category: 'Kepegawaian',
    desc: 'Pengelolaan Guru, NIP, Beban Mengajar & Multi Mata Pelajaran',
    icon: Users,
    colorName: 'sky',
    primaryHex: '#0369A1',
    gradient: 'from-blue-700 via-sky-700 to-indigo-800',
    softBg: 'bg-sky-50/70',
    borderColor: 'border-sky-200',
    badgeBg: 'bg-sky-100',
    badgeText: 'text-sky-900',
    badgeBorder: 'border-sky-300',
    textColor: 'text-sky-800',
    sidebarActiveBg: 'bg-gradient-to-r from-blue-700 to-sky-700',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-sky-600/30',
    iconContainerBg: 'bg-sky-100',
    iconContainerText: 'text-sky-700'
  },
  'admin-mapel': {
    id: 'admin-mapel',
    label: 'Master Mata Pelajaran',
    shortLabel: 'Mata Pelajaran',
    category: 'Kurikulum',
    desc: 'Struktur Kurikulum Nasional, Kelompok Mata Pelajaran & Nilai KKTP/KKM',
    icon: BookOpen,
    colorName: 'rose',
    primaryHex: '#BE123C',
    gradient: 'from-rose-600 via-rose-700 to-pink-700',
    softBg: 'bg-rose-50/70',
    borderColor: 'border-rose-200',
    badgeBg: 'bg-rose-100',
    badgeText: 'text-rose-900',
    badgeBorder: 'border-rose-300',
    textColor: 'text-rose-800',
    sidebarActiveBg: 'bg-gradient-to-r from-rose-600 to-rose-800',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-rose-600/30',
    iconContainerBg: 'bg-rose-100',
    iconContainerText: 'text-rose-700'
  },
  'admin-siswa': {
    id: 'admin-siswa',
    label: 'Master Data Siswa',
    shortLabel: 'Data Siswa',
    category: 'Kesiswaan',
    desc: 'Buku Induk Peserta Didik Seluruh Rombel & Import Excel Dapodik',
    icon: UserSquare2,
    colorName: 'emerald',
    primaryHex: '#059669',
    gradient: 'from-emerald-600 via-teal-600 to-green-600',
    softBg: 'bg-emerald-50/70',
    borderColor: 'border-emerald-200',
    badgeBg: 'bg-emerald-100',
    badgeText: 'text-emerald-800',
    badgeBorder: 'border-emerald-200',
    textColor: 'text-emerald-700',
    sidebarActiveBg: 'bg-gradient-to-r from-emerald-600 to-teal-600',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-emerald-500/25',
    iconContainerBg: 'bg-emerald-100/70',
    iconContainerText: 'text-emerald-600'
  },
  'admin-logo': {
    id: 'admin-logo',
    label: 'Upload Logo Sekolah',
    shortLabel: 'Logo Sekolah',
    category: 'Sistem',
    desc: 'Pengaturan & Unggah Logo Resmi Sekolah, Kop Surat & Bilah Navigasi',
    icon: ImageIcon,
    colorName: 'indigo',
    primaryHex: '#4F46E5',
    gradient: 'from-indigo-600 via-indigo-700 to-indigo-800',
    softBg: 'bg-indigo-50/70',
    borderColor: 'border-indigo-200',
    badgeBg: 'bg-indigo-100',
    badgeText: 'text-indigo-800',
    badgeBorder: 'border-indigo-200',
    textColor: 'text-indigo-700',
    sidebarActiveBg: 'bg-gradient-to-r from-indigo-600 to-indigo-700',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-indigo-500/25',
    iconContainerBg: 'bg-indigo-100/70',
    iconContainerText: 'text-indigo-600'
  },
  'admin-settings': {
    id: 'admin-settings',
    label: 'Pengaturan Aplikasi',
    shortLabel: 'Pengaturan',
    category: 'Sistem',
    desc: 'Profil Lembaga, Kepala Sekolah, Bobot Nilai & Tahun Akademik',
    icon: Sliders,
    colorName: 'zinc',
    primaryHex: '#52525B',
    gradient: 'from-zinc-700 via-zinc-800 to-slate-800',
    softBg: 'bg-zinc-100/70',
    borderColor: 'border-zinc-300',
    badgeBg: 'bg-zinc-200',
    badgeText: 'text-zinc-800',
    badgeBorder: 'border-zinc-300',
    textColor: 'text-zinc-800',
    sidebarActiveBg: 'bg-gradient-to-r from-zinc-700 to-slate-800',
    sidebarActiveText: 'text-white',
    sidebarActiveShadow: 'shadow-md shadow-zinc-600/30',
    iconContainerBg: 'bg-zinc-200',
    iconContainerText: 'text-zinc-700'
  }
};

export const getMenuTheme = (menuId: string): MenuTheme => {
  return (
    MENU_THEMES[menuId] || {
      id: menuId,
      label: 'Administrasi Guru',
      shortLabel: 'Menu',
      category: 'Aplikasi',
      desc: 'Sistem Administrasi Guru Digital',
      icon: LayoutDashboard,
      colorName: 'emerald',
      primaryHex: '#059669',
      gradient: 'from-emerald-600 to-teal-700',
      softBg: 'bg-emerald-50/70',
      borderColor: 'border-emerald-200',
      badgeBg: 'bg-emerald-100',
      badgeText: 'text-emerald-800',
      badgeBorder: 'border-emerald-200',
      textColor: 'text-emerald-700',
      sidebarActiveBg: 'bg-gradient-to-r from-emerald-600 to-teal-600',
      sidebarActiveText: 'text-white',
      sidebarActiveShadow: 'shadow-md shadow-emerald-500/25',
      iconContainerBg: 'bg-emerald-100/70',
      iconContainerText: 'text-emerald-600'
    }
  );
};
